### ISSUE TITLE
MVP Backend Food Commerce

### ISSUE THREAD

**Issue by ardy-yusuf-wibawa** [raffw/food-commerce-backend#2]
# MVP Food Commerce

## Description
Make MVP for backend webapp food commerce

## Summary
Make MVP and deliver as soon as possible to got input and feedback from user

## To-Do
- [ ] make CRUD for data food
- [ ] make CRUD for category
- [ ] make CRUD for promotion
- [ ] make CRUD for order
- [ ] make CRUD for order items
- [ ] make CRUD for carts
- [ ] make CRUD for user
- [ ] Connect the database service to the Apollo service to provide table IDs.
